BEGIN TRAN

DECLARE @UserId NVARCHAR(400) = (SELECT TOP 1 Id FROM AspNetUsers) -- This value will be used for the OwnerId Foreign Key reference from Restaurant table

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Reichel Group', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'French', 1, N'Esmeralda_Gleichner@hotmail.com', N'922-291-1167', N'West Wardfurt', N'940 Rodrick Manor', N'26883-2337', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Lockman Inc', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Vegetarian', 0, N'Stan.Ruecker@hotmail.com', N'(644) 920-6179 x0153', N'Port Gardnertown', N'2775 Royal Heights', N'09282-4591', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Schowalter and Sons', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Italian', 1, N'Rafaela_Schmeler5@yahoo.com', N'(438) 922-7115', N'Herminiostad', N'0297 Frederique Place', N'52445', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Okuneva - Lakin', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'American', 1, N'Austin_Gleichner59@yahoo.com', N'(607) 499-9205 x6084', N'North Brando', N'7146 Mafalda Island', N'19650', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Swift - Hand', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'American', 0, N'Horacio55@yahoo.com', N'981.833.5263', N'Zionville', N'1866 Carolina Expressway', N'76463-9048', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Walter Group', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'American', 1, N'Kayli.Wehner48@yahoo.com', N'(304) 819-4066', N'Lynchberg', N'8287 Clyde Causeway', N'70993-4124', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brakus - Jerde', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Italian', 0, N'Everardo.Bashirian4@gmail.com', N'642-613-7029 x114', N'Leschborough', N'724 Bartoletti Street', N'45001-3862', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brown, Schroeder and Grady', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Mexican', 0, N'Missouri99@hotmail.com', N'606-652-4849 x424', N'Quitzonville', N'6895 Kuvalis Creek', N'21551', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Skiles Group', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Mediterranean', 1, N'Francesca70@yahoo.com', N'841-825-6519 x2606', N'Moenstad', N'7031 Stanton Ferry', N'29309', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Willms, Abbott and Kutch', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'American', 0, N'Scotty67@hotmail.com', N'1-778-863-2851', N'Antonettatown', N'773 Lloyd Field', N'14188', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Douglas, Swaniawski and Cronin', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Vegetarian', 0, N'Mikel_Dicki@gmail.com', N'1-256-308-0729', N'Aufderharland', N'387 Christiana Union', N'01923-9380', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Greenholt Inc', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Japanese', 0, N'Easter_Buckridge27@gmail.com', N'(765) 252-0627', N'Port Lauren', N'526 Kassulke Skyway', N'04170-1505', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rath, Lakin and Krajcik', N'The Football Is od For Training And Recreational Purposes', N'Asian', 0, N'Krista_Becker@hotmail.com', N'947-264-7656 x391', N'Lake Kacey', N'703 Senger Viaduct', N'16320', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Metz, White and Gerlach', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Mediterranean', 0, N'Nigel82@hotmail.com', N'902.763.2070 x63201', N'New Mariela', N'78161 Wilkinson Way', N'69060', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brown, Pagac and Schamberger', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Mexican', 0, N'Camylle59@hotmail.com', N'340-983-3372 x17161', N'McDermottview', N'3155 Levi Isle', N'93562-8524', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Littel - Herman', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Thai', 1, N'Lera_Torphy@gmail.com', N'1-995-907-9170', N'Maggiostad', N'845 Dare Ville', N'05770', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kemmer - Grimes', N'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', N'Mediterranean', 1, N'Eusebio_Jacobi@gmail.com', N'(515) 843-9991', N'North Kaya', N'83198 Barbara Path', N'06306', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Abshire Inc', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'French', 1, N'Stevie87@hotmail.com', N'1-754-536-6345 x85545', N'Lake Pattieberg', N'60517 Harber Lane', N'05038', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hintz Group', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Thai', 0, N'Kyleigh98@gmail.com', N'241.946.2101 x76801', N'Lake Guadalupeshire', N'561 Fritsch Vista', N'08291', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Waelchi - Kessler', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Thai', 1, N'Eugene_Kerluke63@gmail.com', N'1-325-404-3978', N'Tyreseberg', N'6456 Ulises Plain', N'28105-9253', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Halvorson, Fahey and Johns', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Steakhouse', 0, N'Noemi93@gmail.com', N'478-249-6966 x2151', N'North Rossie', N'45177 Dejuan Forges', N'25995-4421', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Koch LLC', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Mexican', 0, N'Corene.Johnston@gmail.com', N'504-491-4208 x390', N'Farrellton', N'973 Heidenreich Knolls', N'05412', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Mohr, McClure and Sanford', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Asian', 0, N'Elinore1@hotmail.com', N'928-746-2873 x09159', N'Erlingport', N'5350 Tia Glens', N'78965-2500', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Boehm Group', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Mediterranean', 1, N'Willy95@hotmail.com', N'536.363.3145 x1469', N'North Nigelview', N'31595 Bogisich Shore', N'10553-7714', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bashirian Group', N'The Football Is od For Training And Recreational Purposes', N'Steakhouse', 0, N'Caleb0@gmail.com', N'1-511-963-4605 x0314', N'Muraziktown', N'32301 Eugenia Station', N'07221-6459', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brown, Breitenberg and McKenzie', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Mexican', 0, N'Pearl34@hotmail.com', N'475-702-1595', N'Jarredtown', N'70125 Santina Curve', N'39604', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Breitenberg - Hoeger', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Steakhouse', 0, N'Christelle.Konopelski85@hotmail.com', N'1-406-717-0789 x462', N'Bogisichland', N'1485 Ivory Tunnel', N'04178-9746', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'O''Kon LLC', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'French', 1, N'Geovanni.Bergstrom@yahoo.com', N'328-491-4306 x57177', N'South Johannborough', N'9152 Koss Ranch', N'61301', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Nolan and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Italian', 0, N'Aiden71@yahoo.com', N'693.847.7545 x563', N'Wilmaberg', N'4915 Schamberger Shores', N'96974-1805', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Feeney, McLaughlin and Abernathy', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Mediterranean', 1, N'Eleonore86@hotmail.com', N'1-653-760-0930 x47057', N'Lake Dakotaport', N'47662 Boyer Walk', N'93193', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bergnaum, Greenholt and O''Keefe', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Asian', 0, N'Jadon68@gmail.com', N'(696) 677-7078 x141', N'Bergnaumside', N'6222 Ryan Mountains', N'42018-1163', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Murray - Hahn', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Steakhouse', 1, N'Garth_Johnson59@hotmail.com', N'1-805-343-9771 x466', N'Lucyborough', N'9806 Tromp Valley', N'30287', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Pfeffer - O''Connell', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'Thai', 0, N'Nia13@gmail.com', N'759-608-1701 x528', N'Lake Keanuhaven', N'301 Leuschke Causeway', N'20675-3044', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Cruickshank, Greenholt and Willms', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'American', 1, N'Ayla_Huels50@yahoo.com', N'(465) 854-1191 x457', N'West Tomas', N'84337 Wiegand Mill', N'55493-0685', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rowe, Koelpin and Halvorson', N'The Football Is od For Training And Recreational Purposes', N'Vegetarian', 1, N'Heath.Turcotte@yahoo.com', N'883-523-2386', N'Kiarahaven', N'73017 Ryan Plaza', N'39488-1943', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Carroll, Koss and Hegmann', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Thai', 1, N'Grant_Moen@gmail.com', N'(914) 959-8086 x5661', N'Lake Annamaehaven', N'791 Maynard Radial', N'28128', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Cassin - Kozey', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Vegetarian', 0, N'Twila_Howell25@gmail.com', N'984.286.7103', N'Miltonstad', N'575 Maudie Loaf', N'01572-7426', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Ratke, Sawayn and Lueilwitz', N'The Football Is od For Training And Recreational Purposes', N'Mediterranean', 1, N'Daisha77@yahoo.com', N'(222) 568-8317', N'South Dillon', N'86771 Olson Plaza', N'76373-0004', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'McClure - Metz', N'The Football Is od For Training And Recreational Purposes', N'Thai', 1, N'Zelda.Leffler@gmail.com', N'996.325.4813 x9505', N'Okunevabury', N'361 Leone Causeway', N'27146-6601', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hoeger - Parisian', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Mexican', 0, N'Madelynn_Runolfsdottir93@gmail.com', N'441-668-5754', N'Port Tito', N'548 Major Meadows', N'71483-2363', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kohler, Romaguera and Roob', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Asian', 1, N'Lavada.Yost15@gmail.com', N'996.642.1788 x420', N'New Torrance', N'26532 Jessie Spur', N'53151', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Morissette Inc', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Mexican', 0, N'Aniya_Grimes95@hotmail.com', N'215-675-5433 x8440', N'Kennafurt', N'00301 Cory Hills', N'92516-1011', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Feest - Senger', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Mediterranean', 1, N'Demetrius_Nicolas@yahoo.com', N'688-319-4590', N'Veldaville', N'523 Kristofer Village', N'11882', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kuhlman - Dicki', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'American', 1, N'Brock_Deckow44@yahoo.com', N'1-739-958-9114 x2925', N'North Marianneberg', N'8130 Joanny Port', N'12944', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Reilly, Heidenreich and Daniel', N'The Football Is od For Training And Recreational Purposes', N'American', 0, N'Andreane_Shields@yahoo.com', N'671-382-3027 x90708', N'South Roderickside', N'83758 Lacey Ways', N'27259-9328', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rodriguez - Roob', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Vegetarian', 0, N'Meggie.Douglas79@hotmail.com', N'(884) 408-8650 x39211', N'North Ismael', N'6172 Haley Ridges', N'99708', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Altenwerth and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'American', 1, N'Justen.Hauck32@gmail.com', N'836-793-8472 x791', N'South Everardohaven', N'6408 Balistreri Port', N'00328', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Daugherty - Turcotte', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'American', 1, N'Brad_Hessel9@gmail.com', N'(738) 291-3142 x159', N'Lake Tarynbury', N'98761 Labadie Mews', N'30847', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Glover Inc', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Mexican', 1, N'Destini25@hotmail.com', N'1-349-385-8561 x130', N'North Kianhaven', N'504 Jamaal Corners', N'59592', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rogahn, Haley and Schumm', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'French', 0, N'Margie_Hegmann@gmail.com', N'1-781-636-8794', N'Hilllstad', N'370 Block Street', N'84693-1848', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Crona - Homenick', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'French', 1, N'Velda_Fadel@gmail.com', N'714-917-1033 x128', N'Dickensport', N'776 Mertz Well', N'69676-9377', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Daugherty Inc', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Asian', 0, N'Noelia79@gmail.com', N'418.634.7033', N'Johnsonshire', N'763 Jerrell Forges', N'99582-2350', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Windler - Hamill', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Japanese', 0, N'Constance.Carroll29@hotmail.com', N'(276) 559-9099 x97863', N'Margaretemouth', N'2779 Marjolaine Garden', N'69570', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Feeney, Toy and Tromp', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Asian', 0, N'Augustine.Hoppe11@yahoo.com', N'991.925.6263 x41755', N'North Janick', N'462 Schneider Path', N'19969-7408', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Muller - Leuschke', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Japanese', 0, N'Leatha_Gerhold@yahoo.com', N'229.825.4782 x194', N'New Gertrudechester', N'4432 Hirthe Mountain', N'27264', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rogahn Inc', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Asian', 0, N'Nico80@gmail.com', N'1-634-750-7456 x5921', N'Lake Pinkie', N'78922 Mertz Mill', N'18601-4907', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'D''Amore Inc', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Asian', 1, N'Pansy19@yahoo.com', N'1-967-597-8126 x0237', N'Bashirianland', N'69669 Brennan Knolls', N'11720-0688', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Daniel - O''Kon', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Asian', 1, N'Mariana.Dare@gmail.com', N'1-990-304-7259 x6634', N'Howardtown', N'333 Nedra Spur', N'52163-6571', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Wiza, Hermann and Medhurst', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'American', 1, N'Emmanuel.Herzog31@gmail.com', N'788-759-8137 x90569', N'Alishaburgh', N'7379 Kasey Flats', N'59782', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Jones and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Mexican', 1, N'Ahmed64@hotmail.com', N'(566) 800-9828', N'Krisburgh', N'02559 Lavonne Trail', N'76052', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Grady Group', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Thai', 1, N'Celestine_Abshire@hotmail.com', N'546.710.6017 x16673', N'East Elainahaven', N'64778 Eliane Row', N'71170-5950', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Gulwski - Lemke', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Mediterranean', 0, N'Sallie47@hotmail.com', N'(458) 200-8840 x64608', N'Conroymouth', N'396 Morar Ways', N'60058', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Schaden, Rau and Jerde', N'The Football Is od For Training And Recreational Purposes', N'Mediterranean', 1, N'Erich.Hoppe90@hotmail.com', N'(399) 603-8941', N'East Julie', N'13824 Steuber Ports', N'72710-1401', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Haag - Fadel', N'The Football Is od For Training And Recreational Purposes', N'Mediterranean', 0, N'Jaime.Braun67@gmail.com', N'(225) 343-6726', N'Hyattstad', N'78691 Aric Turnpike', N'58130-0914', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Dibbert, Abernathy and Braun', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'Thai', 1, N'Trent_Wiza83@gmail.com', N'334.828.4992 x310', N'East Cayla', N'67954 Aimee Views', N'24158-0042', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Russel LLC', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Mexican', 0, N'Vallie_Crist@gmail.com', N'940.276.9488 x77869', N'Port Skylarfurt', N'943 Stiedemann Squares', N'01888-9589', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Marquardt, Feil and O''Conner', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Japanese', 0, N'Montana_Roberts69@yahoo.com', N'(218) 260-0550', N'North Hunter', N'36014 Koss Lights', N'79779', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Barton, Nienow and Smitham', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Steakhouse', 0, N'Arlene.Dicki@gmail.com', N'(821) 776-2212', N'Skilesside', N'5434 Zieme Ports', N'42712', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Maggio, Cole and Jenkins', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Japanese', 0, N'Mathias_Barton@yahoo.com', N'635-508-1086 x521', N'East Marysehaven', N'7677 Walton Village', N'54760', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bechtelar Group', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Steakhouse', 1, N'Donnie_Kautzer91@yahoo.com', N'355.705.2645', N'Jakubowskihaven', N'78919 Ford Drive', N'22872', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Greenfelder Inc', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'French', 0, N'Ericka_Schuster@gmail.com', N'(231) 790-8913', N'East Maribel', N'429 Stracke Spurs', N'89325', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Smith - Reichel', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Asian', 1, N'Wiley_Jakubowski81@gmail.com', N'(967) 271-3014', N'New Minerva', N'1411 Mayert Inlet', N'73523-6425', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Corkery LLC', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Mediterranean', 0, N'Orval.Ruecker@hotmail.com', N'1-728-777-2626 x5301', N'West Aracelymouth', N'96529 Watsica Trafficway', N'60939-2515', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Grimes Group', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Asian', 0, N'Rudolph_Reilly@gmail.com', N'598.467.5407 x4803', N'West Brannon', N'047 McCullough Village', N'50406-2751', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Lueilwitz and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Italian', 1, N'Dixie81@hotmail.com', N'331.621.2177', N'North Herminia', N'63425 Jayda Station', N'13186', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hegmann Inc', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Vegetarian', 0, N'Devan35@hotmail.com', N'909-908-6220 x6120', N'Paolochester', N'6481 Tina Canyon', N'96616', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Jones LLC', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Italian', 1, N'Sanford_Hagenes@hotmail.com', N'(405) 359-2122 x653', N'Ondrickahaven', N'2667 Labadie Forge', N'39092-2108', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Ondricka - Deckow', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Italian', 1, N'Burnice45@hotmail.com', N'228.891.9550 x1033', N'South Rhea', N'7303 Pagac Groves', N'34558', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Windler - Waters', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'American', 0, N'Jaiden_Labadie@gmail.com', N'(329) 611-1753 x0326', N'South Jon', N'2273 Rogahn Drives', N'79569-9500', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Koepp, Upton and Emard', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'American', 1, N'Meggie_Powlowski79@yahoo.com', N'799-947-0137 x828', N'South Robb', N'6063 Nienow Well', N'64668-5717', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bednar, Hoeger and Watsica', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'American', 0, N'Lysanne_Christiansen66@gmail.com', N'653.499.6705', N'Danielville', N'917 Hauck Creek', N'85919', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Aufderhar, Hauck and Pfannerstill', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Mediterranean', 0, N'Lavinia_Dare@gmail.com', N'1-818-682-2462', N'North Brooklynborough', N'654 Berenice Overpass', N'02412', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Labadie, Tillman and Nitzsche', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Mexican', 1, N'Martina.Haley@hotmail.com', N'833.212.2769 x1784', N'Alvinaview', N'6234 Jast Village', N'05370', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kub LLC', N'The Football Is od For Training And Recreational Purposes', N'American', 1, N'Elmira_Hane@hotmail.com', N'1-781-775-4806 x835', N'East Fabiola', N'1504 Konopelski Route', N'07499-5786', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hermann and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'American', 0, N'Wellington.rczany@gmail.com', N'(829) 246-2094 x024', N'Baileyview', N'54037 Amir Trafficway', N'48673-2537', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Trantow, Bayer and Collier', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Asian', 0, N'Conrad.Herman87@yahoo.com', N'614.805.1058', N'West Stanton', N'207 Balistreri Plaza', N'51805-8899', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bogisich, Cartwright and Bode', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'Thai', 0, N'Hermann46@yahoo.com', N'1-834-593-4464 x93693', N'Javonport', N'763 Arjun Union', N'32753-2916', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Gleichner, Hermann and Yost', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'American', 0, N'Leonor17@yahoo.com', N'609.873.4540 x7835', N'Larueville', N'79622 Elliot Flat', N'51200-3061', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Medhurst - Sanford', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'Steakhouse', 1, N'Antwan.Shields48@gmail.com', N'(476) 939-9997 x2726', N'Cronahaven', N'1888 Tommie Corners', N'84428-3950', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Nolan, Simonis and Quitzon', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'French', 0, N'Geraldine.Barrows40@hotmail.com', N'1-415-232-5530', N'New Gloria', N'5235 Myra Mountains', N'40766-1814', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Fritsch - Muller', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'American', 1, N'Drake96@yahoo.com', N'(823) 798-5618 x62655', N'South Damion', N'94118 Garett Route', N'65731-4669', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Cassin Inc', N'The Football Is od For Training And Recreational Purposes', N'Steakhouse', 0, N'Abby70@gmail.com', N'1-817-900-4314', N'Port Vernice', N'3513 Wisoky Passage', N'69267', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Will - Miller', N'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', N'French', 1, N'Jeanette.Okuneva88@gmail.com', N'830-937-9641', N'Antoinettemouth', N'974 Amina Isle', N'13439', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hartmann and Sons', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Steakhouse', 1, N'Tyler42@gmail.com', N'1-913-230-9025 x078', N'East Danstad', N'0974 Merle Ferry', N'29342', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Casper, Kreiger and Collier', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'American', 0, N'Audra_Waelchi@hotmail.com', N'1-852-287-0194 x22356', N'Jonathanland', N'9659 Schimmel Locks', N'33676', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Gislason - Larson', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Steakhouse', 1, N'Jaqueline_Herman@gmail.com', N'569.736.2906', N'Mullerside', N'06039 Sanford Expressway', N'68009', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Huel, Mann and Moen', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Japanese', 1, N'Zane44@gmail.com', N'797-599-5246 x5343', N'Lake Jeramy', N'1789 Kovacek Vista', N'72768', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Rippin, Reynolds and Predovic', N'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design', N'Vegetarian', 0, N'Daphnee75@yahoo.com', N'431-521-3856', N'Kennithbury', N'0317 Sven Roads', N'27005', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bahringer, Bins and Prohaska', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Thai', 0, N'Willie.Greenfelder@yahoo.com', N'748.676.8613', N'Dixiechester', N'5107 Onie Burg', N'88297', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Moen - Collins', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Steakhouse', 1, N'Amelia.King@yahoo.com', N'975-573-6290 x88239', N'North Elaina', N'523 Satterfield Greens', N'45436', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kiehn, Osinski and Kirlin', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Italian', 0, N'Kitty.Stiedemann@yahoo.com', N'322.352.5462', N'New Clay', N'809 Waters Port', N'92041-6468', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Fritsch LLC', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Japanese', 1, N'Rick_Balistreri64@hotmail.com', N'1-823-312-8884 x01975', N'South Erickside', N'2889 Ephraim Islands', N'50594-6972', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Reichel Group', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Thai', 0, N'Christina.Powlowski@gmail.com', N'(570) 893-7808 x715', N'East Willowview', N'428 Hollis Isle', N'97294', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brekke - Hegmann', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'American', 1, N'Ben42@hotmail.com', N'263-533-7742 x21543', N'South Nola', N'2080 Gerhold View', N'68945-2581', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Gutmann, Hodkiewicz and Boyle', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Vegetarian', 1, N'Marcos99@hotmail.com', N'1-224-703-9633', N'West Angelshire', N'6257 Streich Causeway', N'39513', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Green, Russel and Steuber', N'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality', N'Asian', 0, N'Stone79@yahoo.com', N'856-205-9357', N'Schroederport', N'744 Friesen Trail', N'79695-7921', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Adams, Rosenbaum and Schneider', N'Carbonite web alkeeper gloves are ernomically designed to give easy fit', N'Mediterranean', 1, N'Ernie_Davis@hotmail.com', N'(407) 771-2726 x1158', N'Collinsmouth', N'44796 Karson Pike', N'47927-1272', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Dare - Bernhard', N'The Football Is od For Training And Recreational Purposes', N'Italian', 1, N'Gene.Swift@hotmail.com', N'542-496-2042 x1631', N'Lake Dillon', N'7787 Howell Mountains', N'90842', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Dooley - Considine', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'French', 0, N'Nicholaus.West53@gmail.com', N'(614) 979-9154', N'Larsonstad', N'16471 Kilback Walk', N'74490', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Harvey Group', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Vegetarian', 0, N'Elinor52@gmail.com', N'1-553-987-1753 x89420', N'Lubowitztown', N'606 Murazik Flat', N'25741', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hegmann LLC', N'The Football Is od For Training And Recreational Purposes', N'Asian', 0, N'Cecilia.Terry9@yahoo.com', N'315.471.3890 x89178', N'Lucileside', N'6534 Aric Run', N'11079-8156', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kihn - Kessler', N'The Football Is od For Training And Recreational Purposes', N'Mediterranean', 1, N'Kayla76@yahoo.com', N'375-844-8430 x1442', N'Bobbieborough', N'1688 Grant Garden', N'19416-6178', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Murray Inc', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Steakhouse', 0, N'Aliza57@hotmail.com', N'902-821-6021 x7711', N'Lake Alexis', N'54012 McGlynn Turnpike', N'36451', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kunde LLC', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Japanese', 0, N'Marcos37@hotmail.com', N'1-967-433-9030 x550', N'West Dandre', N'8029 Curtis Well', N'66286-5316', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'McKenzie and Sons', N'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals', N'Vegetarian', 1, N'Verna56@yahoo.com', N'483-342-0018 x4484', N'O''Konmouth', N'4594 Smitham Tunnel', N'69773-8304', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Wiegand and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Asian', 0, N'Wendell.Pfeffer@gmail.com', N'(494) 679-2138 x75587', N'Lake Kylee', N'68399 Nils Turnpike', N'64099', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Friesen LLC', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'French', 0, N'Bella1@hotmail.com', N'(395) 315-7293', N'West Catharine', N'9937 Becker Loop', N'35692-8314', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kreiger - Altenwerth', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Japanese', 1, N'Abelardo80@hotmail.com', N'1-927-625-7635 x1492', N'Lucindachester', N'20852 Homenick Drive', N'42695-5729', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Reichert Group', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'French', 0, N'Roxanne_Feest51@gmail.com', N'700.551.5633 x5238', N'Port Kyla', N'537 Ratke Underpass', N'32819-8695', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Kling - Hintz', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'Italian', 1, N'Lindsay.rczany@yahoo.com', N'636.908.9702', N'Lake Roderickside', N'23962 Avery Mount', N'36767', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Dach, Kozey and Stroman', N'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016', N'Thai', 1, N'Mabelle71@hotmail.com', N'(914) 457-3949', N'Lake Oleta', N'211 Jammie Green', N'68851-5025', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Schuppe and Sons', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'French', 1, N'Hermann.Abshire78@gmail.com', N'711.580.4816', N'Port Kadenburgh', N'69094 Berge Flat', N'64012-9507', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Legros, Tremblay and Gibson', N'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', N'Vegetarian', 1, N'Bernhard_Schroeder@hotmail.com', N'1-782-856-4252 x8322', N'North Kristopherfort', N'9682 Carlie Terrace', N'50462', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Brown, Littel and Abbott', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Japanese', 0, N'Chauncey72@gmail.com', N'939-554-0020', N'Lake Tanyafurt', N'256 Genoveva Greens', N'53212', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Upton Group', N'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', N'American', 0, N'Lenny.Greenholt@hotmail.com', N'1-316-641-5082 x84375', N'Fidelport', N'06133 Boyer Groves', N'85317', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Moore, Marquardt and Ernser', N'Boston''s most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles', N'Mexican', 1, N'Judah.Schaefer@hotmail.com', N'453.338.0755 x58496', N'Shyannehaven', N'7647 Watsica Burgs', N'88034', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Flatley, Bashirian and Kuphal', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Japanese', 0, N'Lexie73@gmail.com', N'(673) 466-9070 x916', N'New Annamariechester', N'555 Nienow Flat', N'75583', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Hilll - Hammes', N'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart', N'Asian', 0, N'Jackie56@gmail.com', N'564.380.2125 x4833', N'Lake Doviebury', N'1040 Windler Isle', N'78909-2038', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Bayer - Sawayn', N'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the odness of 100% Natural Ingredients', N'French', 1, N'Blair_Bauch@gmail.com', N'(735) 366-3454 x65029', N'Jacintheborough', N'40068 Talon Turnpike', N'92125', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Balistreri, Stark and Emard', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'Mediterranean', 0, N'Providenci.Jenkins@gmail.com', N'(629) 502-5077', N'Gerlachport', N'580 Wisozk Corners', N'91902-4183', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Watsica, Considine and Schoen', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Mediterranean', 1, N'Philip.Koch@gmail.com', N'1-531-483-2783', N'Port Imanistad', N'0162 Hamill Trace', N'77688-2640', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Mueller, Crooks and Hammes', N'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive', N'Japanese', 1, N'Linda.Bergstrom0@hotmail.com', N'741.603.5732 x314', N'Lake Vada', N'428 ldner Club', N'38788-1424', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Stracke Inc', N'Ernomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support', N'American', 0, N'Dora_Smitham@yahoo.com', N'447.936.2688', N'Stokesside', N'259 Thiel Glens', N'32412-1231', @UserId)

INSERT [dbo].[Restaurants] ([Id], [Name], [Description], [Category], [HasDelivery], [ContactEmail], [ContactNumber], [Address_City], [Address_Street], [Address_PostalCode], [OwnerId]) VALUES (NEWID(), N'Christiansen and Sons', N'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J', N'French', 0, N'Ruben_McKenzie@gmail.com', N'1-748-835-0505 x88068', N'Keelingland', N'778 Jacinthe Crossing', N'36737-2136', @UserId)

SELECT * FROM Restaurants

COMMIT TRAN