@Restaurants.API_HostAddress = https://localhost:7238
@token = CfDJ8NAJC2NnaGxOmapGSTrbOTHlpi2TssNC0FA1BYHZoaASXzsVlpbGh-N4Bh5HhrgZCtW6d2ENGNcsL8VDqEeziD4jbD6fNts_Bvjsxu82A4rAl_2HZBc4N2GFjbybbxUcsxPWaR4ZZALQjLI0FAfsFbACIF7S22aTt4xttiCLSeFgcFg96XPDAx-cGOfD_vrsfeSdVvu6t9OuTHroEN_mwxJD58kVdznWWavPUyq5ReLDyMbueNyQU3K4uZSxKh6MqXVToLkB2khuAb9GBd2zJA3QAyBbzHf62et9PuaYjQnwlm_gRMUoJ5vpAzzBD8aHaLzWBjAKETn7x1t9D51gA1iZ-tDIuSLQ8c-rQ2-TY1cww8qXjEuCrYREiPsWX3jaJvS0D-OVL8NR2qRUcvMEKA_mXzoFkdC4ntc7iJTs8TjLiy6TR_yp9hwgjY3GO5SAnrMovmoL7OnQUUDqGVnO5PBOmHS8UBpevXBLBwAM7bjZWXWD5ccg_AyKjz6DSyrQOgRd4kJgL-P3sTdb2bqhVWYYgQDo78yb93NMwNJEuhDPlWo6Iwbuqjt6ZEXfdpdejIH9_VFARETUtWQmPafjGgTXjKtNq1D3LAkySiQahLHj71LGxXTwjv9LbBzmHx1WyYrctq-vBb-dhWAGlofQrL-YXYVUL8q_KUcFLtrJqqn6LVXQZ-LBxSWEvq1NKCIC7gBEyoLIzrQ7ZqGYbzYcTy_inxuf2BO4a4BxOqeiuY1cMCSMyfaqOTOdijt8cueFADagIuuKcIAxPiNe5-nkEMOBTJVOiseegwPg9935VjwM

GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{be737252-fdb6-4eda-6e1a-08dc7f0257d1}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/932d67a7-3a2f-427f-0a0e-08dc91dbc68e
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelight.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{b01b2f09-bece-4821-24ee-08dc8b8e2435}
Content-Type: application/json

{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###


POST {{Restaurants.API_HostAddress}}/api/restaurants/b01b2f09-bece-4821-24ee-08dc8b8e2435/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta with rich meat sauce.",
  "Price": 12.99,
  "KiloCalories": 599
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/be737252-fdb6-4eda-6e1a-08dc7f0257d1/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/be737252-fdb6-4eda-6e1a-08dc7f0257d1/dishes/44eff1b9-115f-41aa-6c47-08dc7f0257db

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/b01b2f09-bece-4821-24ee-08dc8b8e2435/dishes

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

  {
    "email": "testuser@test.com",
    "password": "Password1!"
  }

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

  {
    "email": "owner@test.com",
    "password": "Password1!"
  }

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Nationality": "Polish",
  "DateOfBirth": "2010-01-01"
}

###
